[package]
# name = "naxia"
name = "wps" # 你懂的
version = "0.1.0"
edition = "2021"

# single process for unlock
[[bin]]
name = "rename"
path = "src/rename.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
walkdir = "2.5.0"
